### ISSUE TITLE
5.0.0 Release Milestone

### ISSUE THREAD

**Issue by nicegamer7** [Multiverse/Multiverse-Core#2418]
## Note: There is no ETA

This issue will track our progress on the upcoming Multiverse 5.0.0. The main goal is to fix bugs, while supporting all the new features of versions beginning with 1.14.4. ~~The reason support for 1.13.2 is being dropped is because newer versions do not function properly with TravelAgent. So, in the effort to provide robust software, support for 1.13.2 will be dropped.~~ (1.13.2 will still be supported, thanks to ben's work in #2580). Here are issues that need to be closed before release:

### Remaining Tasks
- [ ] Remove Deprecated Methods (#2436)
- [ ] Add Tab-Completion
- [ ] Support 1.8+ (if feasible)

### Done
- [x] bStats (#1918 and #2252, closed by #2280)
- [x] Java 15 Support (#2215 and #1939, closed by #2279)
- [x] Multiverse and Bukkit Settings are Different (1.16) (#2318, determined to be a Spigot bug)
- [x] World Properties are not applied to Cloned Worlds until Reboot (#2378, closed by #2379)

### Done
- [x] Issues with Saving Currency Details (Multiverse/Multiverse-Portals#524 and Multiverse/Multiverse-Portals#526)
- [x] plugin.yml missing softdepends (Multiverse/Multiverse-Portals#533, closed by Multiverse/Multiverse-Portals#545)
- [x] Right Clicking with Wand sends two messages (Multiverse/Multiverse-Portals#497, closed by Multiverse/Multiverse-Portals#550)
- [x] Anchors Disappearing from List (#2102, Multiverse/Multiverse-Portals#465, will be closed by #2103)
- [x] NPE when Portal is not specified in command (Multiverse/Multiverse-Portals#571, will be closed by Multiverse/Multiverse-Portals#573)
- [x] Filling a Portal with Flint and Steel on Z Axis (Multiverse/Multiverse-Portals#549, will be closed by Multiverse/Multiverse-Portals#551)
- [x] Portals filled with the Nether Portal Block will act as Nether Portals (Multiverse/Multiverse-Portals#554, will be closed by Multiverse/Multiverse-Portals#584)

### Done
- [x] Players are Bounced Back from MV Portals (Multiverse/Multiverse-Portals#300, closed by Multiverse/Multiverse-NetherPortals#180)
- [x] Error when Bounceback is Disabled and Portal has no Destination (Multiverse/Multiverse-NetherPortals#158, Multiverse/Multiverse-NetherPortals#110, and Multiverse/Multiverse-NetherPortals#104, will be closed by Multiverse/Multiverse-NetherPortals#181)
- [x] Messages sent to Players are Spammed (Multiverse/Multiverse-NetherPortals#157 and Multiverse/Multiverse-NetherPortals#145, will be closed by Multiverse/Multiverse-NetherPortals#181)
- [x] Sometimes Nether Portals are detected as End Portals (Multiverse/Multiverse-NetherPortals#164 and Multiverse/Multiverse-NetherPortals#144, will be closed by Multiverse/Multiverse-NetherPortals#181)
- [x] Linking a World to Itself should Disable Portals (Multiverse/Multiverse-NetherPortals#165, will be closed by Multiverse/Multiverse-NetherPortals#181)
- [x] Teleport Entities to the Correct World (Multiverse/Multiverse-NetherPortals#72, will be closed by Multiverse/Multiverse-NetherPortals#182)

## Multiverse-SignPortals
...

### Done
- [x] Optional Shares break when `optionals_for_ungrouped_worlds` is set to `false` (the `last_location` bug) (Multiverse/Multiverse-Inventories#367)

**Comment by rti** [comment]
> The main goal is to fix bugs, while supporting versions from 1.14.4 to 1.16.2

Is it really 1.16.2? Is there a reason to not support 1.16.3?

**Comment by nicegamer7** [comment]
My mistake, that's a typo. Thanks for pointing it out!

**Comment by Andre601** [comment]
1.16.4 is btw there, so you might update the OP again ;)

But I would wait honestly, as Mojang announced that they will make a 1.16 update to fix severe bugs (Probably that one server-crash bug that has been going around on YouTube for a while now), so it might be 1.16.5 or higher soon.

**Comment by nicegamer7** [comment]
I'm just gonna change it to say latest.

**Comment by TheCompieter** [comment]
Is it possible too merge all the current 5.0.0 pull reguests and compile it without any issues or little issues? or is there already a branch for this cause i would like too test multiverse with the changes.

**Comment by benwoo1110** [comment]
You can try it and see if you want

**Comment by ComPieter1** [comment]
@benwoo1110 
My lack off knowledge to compile and add PR's is very annoying and if you can/would like to can you maybe merge all the 5.0.0 stuff into the main 5.0.0 branch? I would appreciate that very much if possible. Or do you maybe know when the 5.0.0 is roughly done/ready?

**Comment by benwoo1110** [comment]
There is no ETA, sorry. The PRs will get merge when it's ready and tested to be working.

**Comment by ComPieter1** [comment]
Thanks.

**Comment by PappoYT** [comment]
Hello @benwoo1110 
have you any update for an ETA of 5.0.0 version? TY

**Comment by benwoo1110** [comment]
No

**Comment by TheJoshue** [comment]
will this work on 1.8+ and java8+?

**Comment by benwoo1110** [comment]
No plans to support anything below 1.12. Any updates will be updated accordingly, locking as significant number of no value comment is posted. If anyone have a genuine point to say, contact us at discord.

**Comment by benwoo1110** [comment]
Its released!
